CREATE TABLE CUSTOMER (
    C_ID INT PRIMARY KEY,
    C_NAME VARCHAR2(50) NOT NULL,
    C_ADDRESS VARCHAR2(100),
    C_PHONE VARCHAR2(15)
);
CREATE TABLE PRODUCT (
    P_ID INT PRIMARY KEY,
    P_NAME VARCHAR2(50) NOT NULL,
    P_PRICE DECIMAL(10, 2) NOT NULL
);
CREATE TABLE ORDERS (
    O_ID INT PRIMARY KEY,
    O_DATE DATE NOT NULL,
    C_ID INT,
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID)
);
CREATE TABLE ORDER_DETAILS (
    OD_ID INT PRIMARY KEY,
    O_ID INT,
    P_ID INT,
    QUANTITY INT,
    FOREIGN KEY (O_ID) REFERENCES ORDERS(O_ID),
    FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID)
);
ALTER TABLE PRODUCT
ADD Catégorie VARCHAR2(20);

ALTER TABLE ORDERS
ADD OrderDate DATE DEFAULT SYSDATE;

